UI kit input
profydev/prolog-app-JorgeAMendoza pull request #21
Opened 2023-12-20 12:43 UTC by JorgeAMendoza

Create `Input` element from the UI kit, apply various stylings and states and implement the component into the `filter` options.

2023-12-20 20:12 UTC, romanchukenator requested changes
Just one thing about using truthy/falsey values.

2023-12-20 20:12 UTC, romanchukenator commented on features/ui/input/Input.tsx
> +  errorText?: string;
You could likely just use the `errorText` to figure if there's an error or not.

2023-12-20 20:12 UTC, romanchukenator commented on features/ui/input/Input.tsx
> +      {error && <span className={style.errorText}>{errorText}</span>}
These still work with `{errorText && <span className={style.errorText}>{errorText}</span>}`, etc.

2023-12-20 20:16 UTC, romanchukenator commented on features/ui/input/Input.tsx
> +      aria-label={!label ? ariaText : ""}
```suggestion
      aria-label={label ? "" : ariaText}
```

It's kinda 🌵 a nitpick but I personally try to avoid inverting checked values because of the additional cognitive overhead of having to read lines of code while keeping track of things like "if this is true then it's actually false"

2023-12-20 20:17 UTC, romanchukenator commented on features/ui/input/Input.tsx
> +      {label ? <span className={style.labelText}>{label}</span> : null}
```suggestion
      {label && <span className={style.labelText}>{label}</span>}
```

2023-12-20 20:18 UTC, romanchukenator commented on features/ui/input/Input.tsx
> +      {label ? <span className={style.labelText}>{label}</span> : null}
...and the same comment for any place you use a ternary check to possibly resolve to `null`

2023-12-20 20:20 UTC, JorgeAMendoza commented on features/ui/input/Input.tsx
> +  errorText?: string;
According to the Figma design, an input can have an error and not error text, wouldn't just using `errorText` make it difficult to render the "no error text but error" input style?

2023-12-20 20:21 UTC, JorgeAMendoza commented on features/ui/input/Input.tsx
> +      {error && <span className={style.errorText}>{errorText}</span>}
It would probably be best to check against `errorText` instead of `error` when determining to render the error text. This will be changed.

2023-12-20 20:29 UTC, JorgeAMendoza commented on features/ui/input/Input.tsx
> +      aria-label={!label ? ariaText : ""}
I agree with this, sometimes I invert the checks mistakenly! Will be committed.

2023-12-20 20:30 UTC, romanchukenator commented on features/ui/input/Input.tsx
> +  errorText?: string;
Oh, interesting. Right you are. Sorry about that.

I would push back about not showing an error message but the designs say otherwise! 🤷

2023-12-20 20:30 UTC, romanchukenator approved these changes

2023-12-20 20:36 UTC, JorgeAMendoza commented on features/ui/input/Input.tsx
> +      {label ? <span className={style.labelText}>{label}</span> : null}
I prefer to use the ternary operator in this case in React is because I want to be deliberate about what I want to render in the component. By stating null, react knows not to render anything, but with `&&`, react my potentially render the component. In this case its not a big deal, but if the element was going to be rendered based on a API call, `&&` would throw an error on the initial render because it does not have the data yet! I just realized I mixed how I rendered text this way and need to make it consistent!

I hope I explained it right, here is a article detailing the differences: https://kentcdodds.com/blog/use-ternaries-rather-than-and-and-in-jsx

2023-12-26 21:11 UTC, mentor-tara approved these changes
Go go go :smile:[](prolog-21)

2023-12-26 21:12 UTC, merged